ArneBinder/pie-datasets

.github/workflows/test.yaml
The default `.codecov` file is not supported (see [here](https://docs.codecov.com/docs/supported-report-formats#non-supported-code-coverage-formats)), so we explicitly create a xml file and upload that.
=> fix codecov upload

tests/conftest.py
by importing all python files in `src` and `dataset_builders` in `conftest.py` to include them in coverage calculation
=> fix coverage score (and report) for unused source files

dataset_builders/pie/conll2003/README.md, dataset_builders/pie/conll2003/conll2003.py, tests/dataset_builders/pie/test_conll2003.py
This adds the [conll2003](https://aclanthology.org/W03-0419/) dataset. See [here](https://huggingface.co/datasets/conll2003) for the respective Huggingface dataset card.
=> add conll2003 dataset

.github/workflows/test.yaml
...because this is already ensured by codecov
=> do not assert minimum test coverage via pytest 

dataset_builders/pie/brat/brat.py, src/pie_datasets/document/types.py, tests/dataset_builders/pie/test_brat.py
because they should be usable in converter methods that need to be implemented external for the generic BRAT dataset
=> make BRAT document types exportable

dataset_builders/pie/brat/requirements.txt, pyproject.toml
This also increases the minimum required `pie-datasets` version for the `brat` dataset script.
=> release 0.3.1

src/pie_datasets/core/__init__.py, src/pie_datasets/core/dataset_dict.py, tests/unit/core/test_dataset_dict.py
This implements the method `pie_datasets.load_dataset` which behaves similar to `datasets.load_dataset`, i.e. it returns either a `pie_datasets.(Iterable)Dataset` if `split` is provided or a `pie_datasets.DatasetDict` otherwise.
=> implement `load_dataset`

dataset_builders/pie/brat/brat.py, dataset_builders/pie/cdcp/cdcp.py, dataset_builders/pie/conll2003/conll2003.py, dataset_builders/pie/tacred/tacred.py, src/pie_datasets/core/builder.py
This PR adds the attributes `BASE_DATASET_REVISION` and `BASE_DATASET_REVISIONS` (useful to set different values for different dataset names) to the dataset builder class. 
It is strongly recommended to set them for any dataset script so that any changes in the base (Huggingface) dataset script does not impact the PIE dataset script!
=> add `BASE_DATASET_REVISION` and `BASE_DATASET_REVISIONS` to the dataset builder

src/pie_datasets/core/builder.py
This PR makes `document_converters` a property of `PieDatasetBuilder` so that derived builders can overwrite it with logic that depend on the dataset variant (i.e. `self.config.name`).
=> `document_converters` as property of `PieDatasetBuilder`

src/pie_datasets/document/processing/__init__.py, src/pie_datasets/document/processing/relation_argument_sorter.py, tests/unit/document/processing/test_relation_argument_sorter.py
This PR adds an `RelationArgumentSorter` to the `document.processing` package. From the docstring:
```
Sorts the arguments of the relations in the given relation layer. The sorting is done by the
start and end positions of the arguments. The relations with the same sorted arguments are
merged into one relation.
Args:
relation_layer: the name of the relation layer
label_whitelist: if not None, only the relations with the label in the whitelist are sorted
inplace: if True, the sorting is done in place, otherwise the document is copied and the sorting is done
on the copy
```
This is useful, for instance, to create deterministic entries for symmetric relations if it is not intended to keep both relations for one argument pair.
=> add document processor: `RelationArgumentSorter`

dataset_builders/pie/brat/requirements.txt, dataset_builders/pie/cdcp/requirements.txt, dataset_builders/pie/conll2003/requirements.txt, dataset_builders/pie/scidtb_argmin/requirements.txt, dataset_builders/pie/tacred/requirements.txt
This sets max versions for `pie-datasets` in the dataset loading scripts to avoid any breaking in the future . It also fixes #55.
=> fix `pie-datasets` version ranges in dataset loading scripts

dataset_builders/pie/cdcp/requirements.txt, dataset_builders/pie/scidtb_argmin/requirements.txt, dataset_builders/pie/tacred/requirements.txt, poetry.lock, pyproject.toml
This PR makes `pie-modules` a dev dependency and adds it to the respective dataset script requirements.
=> make `pie-modules` a dev dependency

dataset_builders/pie/brat/brat.py, src/pie_datasets/builders/brat.py
This PR implements #84. We update the revision for the `Brat` builder to the version with the encoding fix for windows (https://huggingface.co/datasets/DFKI-SLT/brat/commit/844de61e8a00dc6a93fc29dc185f6e617131fbf1).
This is **breaking** because we set the `BASE_DATASET_REVISION` for the generic `BratBuilder` back to `None` (this should just be set in derived builders).
=> Fix brat revisions

src/pie_datasets/core/builder.py
For now, these methods are not effectively used. But they will serve as a common interface for back conversion to Huggingface dataset instances.
=> add `_generate_example()` and `_generate_example_kwargs()` to `PieDatasetBuilder`

dataset_builders/pie/squad_v2/README.md, dataset_builders/pie/squad_v2/requirements.txt, dataset_builders/pie/squad_v2/squad_v2.py, poetry.lock, pyproject.toml, tests/dataset_builders/pie/test_squad_v2.py
This adds the `squad_v2` dataset, see [here](https://huggingface.co/datasets/squad_v2) for the Huggingface dataset card.
TODO:
- ~[ ] use tests with just a dataset extract, mark other tests with `@pytest.mark.slow`~ the HF dataset script does nto allow to set a `data_dir`
=> add `squad_v2` datasets

poetry.lock, pyproject.toml, tests/dataset_builders/pie/test_sciarg.py
Before this PR, the partition annotations were not used at all for the tokenization in the tests with docuements that have partitions.
=> fix sciarg tests: tokenization with partitions

poetry.lock, pyproject.toml
This prevents the errors introduced by https://github.com/huggingface/datasets/pull/6448. See #93 for more context.
=> pin datasets to <0.16.0

dataset_builders/pie/cdcp/cdcp.py, tests/dataset_builders/pie/test_cdcp.py
This PR updates the revision of the `cdcp` base dataset to [3cf79257900b3f97e4b8f9faae2484b1a534f484](https://huggingface.co/datasets/DFKI-SLT/cdcp/commit/3cf79257900b3f97e4b8f9faae2484b1a534f484), i.e. the broken example (id=00410) is skipped. This fixes #98.
=> `cdcp` dataset: use fixed HF dataset

tests/dataset_builders/pie/test_squad_v2.py
This consistently splits the tests in fast and slow tests, where the former touch only the first two instances of the training set and the latter apply to all instances, but they are flagged with `@pytest.mark.slow` (i.e. they do not run on the GitHub CI).
It decreases the runtime of the `test` workflow on GitHub CI from `7m 21s` to `6m 13s`.
context: #107
=> decrease `squad_v2` test time

tests/dataset_builders/pie/test_imdb.py
Same as #108, but for the `imdb` datasets: This consistently splits the tests in fast and slow tests, where the former touch only the first two instances of the training set and the latter apply to all instances, but they are flagged with @pytest.mark.slow (i.e. they do not run on the GitHub CI).
This decreases the runtime for the `test` workflow on GitHub CI from `5m 27s` to `xxx`
context: #107
=> decrease `imdb` test time

.github/workflows/test.yaml
... from 10 to 30 minutes. Context: #107
=> increase timeout for test CI job

tests/dataset_builders/pie/test_cdcp.py
To mitigate that the tests break if the source data (https://facultystaff.richmond.edu/~jpark/data/cdcp_acl17.zip) is not available, we use a local copy for all tests of the `cdcp` dataset. Previously, that was just the case for the HF related dataset tests.
=> use local data for `cdcp` pie dataset tests

.coveragerc, .github/workflows/test.yaml, .github/workflows/test_datasets.yaml, src/pie_datasets/builders/brat.py, tests/unit/builder/test_brat_builder.py
This PR outsources tests to new `test_datasets.yaml` GitHub CI workflow. This is the first approach to handle #112.
The following items in the workflow configs are adjusted:
- `on.(push|pull_request).paths(-ignore)`: only execute the workflow if the respective files did change
- add `--ignore=tests/dataset_builders` / `tests/dataset_builders` to `pytest` arguments: only execute the respective tests
- set `--cov=src` / `--cov`: only calculate the coverage for the respective files
- `coverage.xml` / `coverage_datasets.xml` to save and upload the coverage report
Notes:
- this also adds new tests for the `BratBuilder`. Until now, this was covered by the Brat dataset tests, but since these are now separated, we also need explicit tests for the builder.
- this also implements …
=> separate test forkflow for datasets

poetry.lock, pyproject.toml, src/pie_datasets/builders/brat.py, tests/unit/builder/test_brat_builder.py
This requires [pytorch-ie>=0.30.3](https://github.com/ArneBinder/pytorch-ie/releases/tag/v0.30.3). It raises the minimum minor pytorch-ie version, so this is breaking.
=> brat: use annotation types from pytorch-ie

.github/workflows/test_pie_datasets.yaml
... to 15 minutes (otherwise the test for `conll2012_ontonotesv5` fails)
=> increase timeout for test_dataset CI job 

dataset_builders/pie/aae2/aae2.py
In this case, the `BUILDER_CONFIG_CLASS` is used to create a new config from scratch. However, we still need to pass `merge_fragmented_spans=True`, otherwise we get documents in an unexpected format:  `BratDocument` which has multi-spans, but we want `BratDocumentWithMergedSpans` with simple spans. This PR sets the `BUILDER_CONFIG_CLASS` and hardcodes `merge_fragmented_spans=True`.
=> fix `aae2` when passing `conversion_method` to `load_dataset`

poetry.lock, pyproject.toml
to fix breakage with datasets and update dependencies
Note: All tests for the individual dataset builders passed locally.
=> set max numpy version to <2.0.0 

dataset_builders/pie/biorel/biorel.py
in `convert_to_text_document_with_labeled_spans_and_binary_relations `. This was missed in #134. 
Having the warning was a problem because it happened quite often, e.g. at least 200 times for train set with length of 114000, which would spam the console when using the converter.
=> biorel: remove warning when entity name is not the same as the span text

poetry.lock, pyproject.toml
This PR adds dependencies for torch in macOS with M-series. Currently tested on M1 only.
=> poetry dependencies for torch in macOS with M-series

src/pie_datasets/builders/brat.py, tests/unit/builder/test_brat_builder.py
This PR handles the note annotations by creating a `BratNote` data class. Note annotations are the free form text in brat annotation file that targets either a document or an annotation. `BratNote` is added to `BratDocument` as well as `BratDocumentWithMergedSpans`. `BratNote` targets *all* other annotation layers. 
`resolve()` method is added to both `BratNote` and `BratAttribute` that returns the value, label and the annotation associated with the `BratNote` as well as BratAttribute.
=> add brat note

src/pie_datasets/core/dataset.py, tests/unit/core/test_dataset.py
=> implement `Dataset.from_documents`

src/pie_datasets/core/__init__.py, src/pie_datasets/core/dataset.py, tests/unit/core/test_dataset.py
Implementing a method for the concatenation of multiple datasets into one single dataset.
=> add concatenate datasets method

src/pie_datasets/core/dataset_dict.py, tests/unit/core/test_dataset_dict.py
from the docstring: 
```
set_batch_size_to_split_size: If enabled, set the batch_size to the size of the respective split
when calling map() on it. This is useful to transform whole splits when using it in
combination with batched=True.
```
=> add parameter `set_batch_size_to_split_size` to `DatasetDict.map`

dataset_builders/pie/sciarg/sciarg.py, tests/dataset_builders/pie/sciarg/test_sciarg.py
This PR
- adds a test that asserts label counts for `labeled_partitions`
- changes `RegexPartitioner` `pattern` to `"<([^>/]+)>(?s:.)*?</\\1>"`: find matching tags non-greedy (`*?`), allow newlines in between (`s` flag) and capture the tag name
This affects only document A32 where the abstract was not identified before but now it is.
=> `sciarg`: fix partitioning

src/pie_datasets/core/dataset_dict.py, tests/unit/core/test_dataset_dict.py
`concatenate_dataset_dicts()` now accepts both `str` and `list[str]` as a source split value. This allows to merge different splits of same dataset.
=> Extend split_mappings format in `concatenate_dataset_dicts()`

dataset_builders/pie/sciarg/README.md, dataset_builders/pie/sciarg/sciarg.py, tests/dataset_builders/pie/sciarg/test_sciarg.py
Until now, it was missed that the `contradicts` relation is symmetric (see [SciArg guidelines](https://data.dws.informatik.uni-mannheim.de/sci-arg/annotation_guidelines.pdf), page 3). This PR adds the `contradicts` relations to the ones that get direction normalized. Note that this has only an effect to the converted dataset!
This also fixes the relation labels in some tables in the readme.
=> `sciarg` dataset: fix `contradicts` is symmetric

dataset_builders/pie/aae2/aae2.py, tests/dataset_builders/pie/aae2/test_aae2.py
- implemented via `document_converters`, so it has just an effect when using them, i.e. by calling `.to_document_type()`
- just one document converter `TextDocumentWithLabeledSpansBinaryRelationsAndLabeledPartitions`: uses `conversion_method=connect_all`, but remove all cross partition (i.e. cross paragraph) relations
usage:
```python
from pie_datasets import load_dataset
from pytorch_ie.documents import TextDocumentWithLabeledSpansBinaryRelationsAndLabeledPartitions
aae2 = load_dataset("dataset_builders/pie/aae2", name="paragraphs").to_document_type(TextDocumentWithLabeledSpansBinaryRelationsAndLabeledPartitions)
```
=> aae2 dataset: implement `paragraphs` variant

.github/workflows/code-quality-main.yaml, .github/workflows/code-quality-pr.yaml, .github/workflows/labeler.yml, .github/workflows/release.yml, .github/workflows/test.yaml
especially for `actions/cache` to fix the version issue, see https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down for context
Note that our actions did not succeed although we use `actions/cache >= 4` (`v4.2.1`).
Same as https://github.com/ArneBinder/pie-modules/pull/156.
=> CI: define only major version for all actions from Github

src/pie_datasets/core/dataset_dict.py, tests/unit/core/test_dataset_dict.py
from the docstring:
```
downcast: if `True` (default), the dataset is converted to the new document type even
if it already has a document type that is a superclass of the new document type.
If `False`, no conversion is done in this case.
```
Since `True` is the default, which was the behavior until now, this is *not* breaking.
=> add parameter `downcast` to `DatasetDict.to_document_type`

dataset_builders/pie/conll2003/conll2003.py, dataset_builders/pie/conll2003/requirements.txt, dataset_builders/pie/scidtb_argmin/requirements.txt, dataset_builders/pie/scidtb_argmin/scidtb_argmin.py, poetry.lock, pyproject.toml, tests/unit/core/test_dataset.py
in `conll2003` and `scidtb_argmin` dataset loader to get rid of `pytorch-ie`. See #178 and https://github.com/ArneBinder/pie-core/issues/17 for context.
TODO:
=> use `pie_modules.utils.sequence_tagging`

dataset_builders/pie/aae2/requirements.txt, dataset_builders/pie/cdcp/requirements.txt, dataset_builders/pie/conll2012_ontonotesv5/requirements.txt, dataset_builders/pie/sciarg/requirements.txt, dataset_builders/pie/squad_v2/requirements.txt, dataset_builders/pie/tacred/requirements.txt, tests/dataset_builders/pie/abstrct/additional-requirements.txt, tests/dataset_builders/pie/argmicro/additional-requirements.txt, tests/dataset_builders/pie/drugprot/additional-requirements.txt
This directly affects:
- `aae2`
- `cdcp`
- `conll2012_ontonotesv5`
- `sciarg`
- `squad_v2`
- `tacred`
and via test dependencies (for tokenization tests):
- `abstract`
- `argmicro`
- `drugprot`
=> increase maximum allowed version of `pie-modules` for all individual datasets to `<0.16.0`

.github/workflows/code-quality-main.yaml, .github/workflows/code-quality-pr.yaml, .github/workflows/test.yaml, README.md, poetry.lock, pyproject.toml
The `dev` dependencies should not be installed per default in any packages that require `pie-datasets`.
After this, it is required to install via `poetry install --with dev` for development purposes, e.g., any testing etc. (this is also reflected in the [README.md](https://github.com/ArneBinder/pie-datasets/blob/main/README.md#development)).
=> make `dev` dependencies optional

src/pie_datasets/core/dataset_dict.py, tests/unit/core/test_dataset_dict.py
from the docstring:
```
mode: mode for writing the data. Can be either "a" (append) or "w" (overwrite). Default is "a".
```
We use `"a"` as default to be backwards compatible. This should be adjusted to `"w"` in the next breaking release. 
partly implements #158
=> add parameter `mode` to `DatasetDict.to_json`

tests/fixtures/builder/datasets/default_config_kwargs/default_config_kwargs.py, tests/fixtures/builder/datasets/multi_config/multi_config.py, tests/fixtures/builder/datasets/name_mapping/name_mapping.py, tests/fixtures/builder/datasets/name_mapping_disabled/name_mapping_disabled.py, tests/fixtures/builder/datasets/single_config/single_config.py, tests/fixtures/builder/datasets/wrong_builder_class_config/wrong_builder_class_config.py, tests/unit/core/test_dataset_dict.py
since `TextDocument` is deprecated
=> use `TextBasedDocument` instead of `TextDocument` in tests

poetry.lock, pyproject.toml
implements #197, also see https://github.com/ArneBinder/pytorch-ie/issues/489
follow-up: when `pytorch-ie` is not used anymore (#178 + `pie-modules` release including https://github.com/ArneBinder/pie-modules/pull/187 for tests), check if this is really still necessary
=> pin `fsspec` to `<2023.9.0`

src/pie_datasets/core/builder.py, src/pie_datasets/core/dataset.py, tests/conftest.py, tests/unit/core/test_dataset.py
This PR implements `(Iterable)Dataset.map_to_hf()` and use it in `.map()` (from where it was outsourced):
```
Map the (iterable) dataset using a function and return a Huggingface (Iterable)Dataset.
Args:
function (Optional[Callable], optional): The function to apply to the documents. Defaults to None.
as_documents (bool, optional): Whether the function returns documents. Defaults to False.
**map_kwargs: Additional keyword arguments for the Huggingface (Iterable)Dataset.map method.
```
In addition, it implements the changes below. 
testing:
- add tests for map with empty datasets
- add tests for `as_documents=False`
fixes:
- fix usage of `as_documents` for `IterableDataset.map()`: it now behaves identical as for `Datset.map()`, i.e., it signals "Whether the function returns documents. …
=> implement `(Iterable)Dataset.map_to_hf()`

codecov.yml, src/pie_datasets/builders/brat.py
implement `BratRelation`, `BratSpan`, `BratMultiSpan` and `BaseBratDocument` and use them in `BratDocument` and `BratDocumentWithMergedSpans`
**This changes the types `BratDocument` and `BratDocumentWithMergedSpans`, so this is breaking!** This affects the datasets: `aae2`, `brat`, and `sciarg`.
This PR also decreases the patch codecov target to 84%.
Requires: #196
Follow-ups:
=> make brat documents independent of `pie-modules`

src/pie_datasets/builders/brat.py, tests/unit/builder/test_brat_builder.py
This PR adds a breaking change to the previous implementation of annotation attributes in `BratDocument` and `BratDocumentWithMergedSpans`. Previously, both of these documents had separate layers for span and relation attributes as `span_attributes` and `relation_attributes` respectively. With the new changes, the attributes are stored in each document's `attribute` layer, which targets spans *and* relations.
The following example shows how annotation attributes can be added:
```diff
span_attribute = BratAttribute(annotation=span, label="actual")
- doc.span_attributes.extend(span_attribute)
+ doc.attributes.append(span_attribute)
assert span_attribute.resolve() == (True, "actual", ("person", "Jane"))
```
follow-up (should happen after the breaking release):
=> update brat attribute layers
